# 1. Сборка (Build)
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2. Раздача через Nginx (Serve)
FROM nginx:alpine
# Копируем собранные файлы React в папку Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Копируем конфиг Nginx (создадим его ниже)
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]