# Generated by Django 4.2.27 on 2025-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryconfig',
            name='template_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Колонки в шаблоне Excel'),
        ),
    ]
