# Generated by Django 4.2.27 on 2025-12-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_trigger_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryconfig',
            name='public_list_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Поля Публичной Таблицы'),
        ),
    ]
