# Generated by Django 4.2.26 on 2025-12-03 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inn',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('SUPPLIER', 'Поставщик (Юр.лицо)'), ('USER', 'Обычный пользователь')], default='USER', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('is_manufacturer', models.BooleanField(default=False, verbose_name='Мы - Производитель')),
                ('is_importer', models.BooleanField(default=False, verbose_name='Мы - Импортер')),
                ('is_exporter', models.BooleanField(default=False, verbose_name='Мы - Экспортер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
